import { MaterialLeadTime } from './types';

export const INITIAL_LEAD_TIMES: Omit<MaterialLeadTime, 'id' | 'leadTimeDays' | 'purchaseTimeDays' | 'manufacturingTimeDays' | 'ownerId'>[] = [
  { category: '1. Estructura principal', subCategory: '1.1 Chapones para estructura principal' },
  { category: '1. Estructura principal', subCategory: '1.2 Perfiles laminados en caliente para estructura principal' },
  { category: '2. Pletinas' },
  { category: '3. Medios de unión', subCategory: '3.1 Uniones principales' },
  { category: '3. Medios de unión', subCategory: '3.2 Uniones secundarias' },
  { category: '4. Estructura secundaria', subCategory: '4.1 Correas de cubierta' },
  { category: '4. Estructura secundaria', subCategory: '4.2 Correas de lateral' },
  { category: '4. Estructura secundaria', subCategory: '4.3 Tensores' },
  { category: '4. Estructura secundaria', subCategory: '4.4 Tillas' },
  { category: '4. Estructura secundaria', subCategory: '4.5 Tornapuntas' },
  { category: '5. Aislación', subCategory: '5.1 Aislante' },
  { category: '5. Aislación', subCategory: '5.2 Malla Tenax' },
  { category: '5. Aislación', subCategory: '5.3 Cintas e insumos' },
  { category: '6. Cerramientos', subCategory: '6.1 Chapas de cubierta' },
  { category: '6. Cerramientos', subCategory: '6.2 Chapas de lateral' },
  { category: '6. Cerramientos', subCategory: '6.3 Paneles de cubierta' },
  { category: '6. Cerramientos', subCategory: '6.4 Paneles de lateral' },
  { category: '6. Cerramientos', subCategory: '6.5 Insumos de cubierta' },
  { category: '6. Cerramientos', subCategory: '6.6 Insumos de lateral' },
  { category: '7. Zinguerías', subCategory: '7.1 Chapa prepintada' },
  { category: '7. Zinguerías', subCategory: '7.2 Chapa galvanizada' },
  { category: '7. Zinguerías', subCategory: '7.3 Compriband' },
  { category: '8. Canaletas', subCategory: '8.1 Chapa para canaleta' },
  { category: '8. Canaletas', subCategory: '8.2 Grampas' },
  { category: '8. Canaletas', subCategory: '8.3 Tillas' },
  { category: '8. Canaletas', subCategory: '8.4 Boquetas y bajadas' },
  { category: '9. Premoldeados', subCategory: '9.1 Losetas' },
  { category: '10. Tratamiento superficial', subCategory: '10.1 Fondo epoxi' },
  { category: '10. Tratamiento superficial', subCategory: '10.2 Poliuretano' },
  { category: '10. Tratamiento superficial', subCategory: '10.3 Diluyente' },
];
